### ISSUE TITLE
improve graphs

### ISSUE THREAD

**Issue by simonpedrogonzalez** [simonpedrogonzalez/opencluster#12]

**Comment by mchalela** [comment]
If you want to provide plots I suggest you look at this project implementation with attrs: https://github.com/ngrion/apode

Check for example the class `ApodeData` in `apode/basic.py`. They add a plot attribute that is not an initialization argument (`init=False`) and they provide a plot accsesor
```python
    @plot.default
    def _plot_default(self):
        return PlotAccsesor(idf=self)
```
The object `PlotAccsesor` is defined in the module `apode/plots.py` and adds a few different plotting options and some private methods for auxiliary computations necessary for plotting. This is probably the cleanest way to implement plot features. 

You will also need to test your plots using the `matplotlib.testing` module. You can see some examples in their `tests/test_plots.py` module.

**Comment by mchalela** [comment]
For now remove all your plotting functions from your methods. Make a draft directory and save a copy of opencluster.py for latter.
Remove matplotlib from your dependencies.
